const DEFAULT_CONNECTION_STROKE = 'darkred'

const DEFAULT_FONT_FAMILY = 'Courier New'

const DEFAULT_FONT = `10pt ${DEFAULT_FONT_FAMILY}`

const DEFAULT_LABEL_FILL = 'rgba(204,0,0,0.9)'

const DEFAULT_LOC_FILL = 'rgba(0,255,127,.9)'

const DEFAULT_RADIUS = 10

const DEFAULT_SELECTION_STROKE = '#F6B'

export {
  DEFAULT_CONNECTION_STROKE,
  DEFAULT_FONT,
  DEFAULT_FONT_FAMILY,
  DEFAULT_LABEL_FILL,
  DEFAULT_LOC_FILL,
  DEFAULT_RADIUS,
  DEFAULT_SELECTION_STROKE,
}
