const DEFAULT_CONNECTION_STROKE = 'darkred'

const DEFAULT_FONT_FAMILY = 'Courier New'

const DEFAULT_FONT = `10pt ${DEFAULT_FONT_FAMILY}`

const DEFAULT_LABEL_FILL = '#cc0000'

const DEFAULT_LOC_FILL = '#00ff7f'

const DEFAULT_RADIUS = 10

const DEFAULT_SELECTION_STROKE = '#FF66BB'

export {
  DEFAULT_CONNECTION_STROKE,
  DEFAULT_FONT,
  DEFAULT_FONT_FAMILY,
  DEFAULT_LABEL_FILL,
  DEFAULT_LOC_FILL,
  DEFAULT_RADIUS,
  DEFAULT_SELECTION_STROKE,
}
